# .github/workflows/generate-test-plan.yml

name: Generate QA Test Plan with Groq

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  test-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get PR diff
        run: git diff origin/main...HEAD > diff.txt

      - name: Generate Test Plan with Groq
        run: python generate_test_plan.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GROQ_MODEL: llama3-70b-8192
